![image info](https://user-images.githubusercontent.com/91945811/146929832-e78ff1f4-2739-41b1-acd3-019a39b6a42c.png)
<div style="float: right; font-size: small;">
    Erstellt von Fakher Ahmed für Data Science. Institut by Fabian Rappert
</div>

# Datenbereinigung und Sortierung mit Pandas

## Laden des Datensatzes
Lade den Datensatz und untersuche seine Struktur.

#### Schritte:
1. Importiere die benötigten Bibliotheken.
2. Lade die Datei `Sales_April_2019.csv` mit Pandas.
3. Zeige die ersten 10 Zeilen der Daten an.
4. Überprüfe die Datentypen der Spalten und wandele gegebenfalls um.

In [1]:
# Bibs Laden
import pandas as pd

# Daten in einen DataFrame laden
sales_data = pd.read_csv("Data/Sales_April_2019.csv")

In [2]:
# Erste 10 Zeilen anzeigen
sales_data.head(10)

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
1,NaN,NaN,NaN,NaN,NaN,NaN
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
5,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001"
6,176562,USB-C Charging Cable,1,11.95,04/29/19 13:03,"381 Wilson St, San Francisco, CA 94016"
7,176563,Bose SoundSport Headphones,1,99.99,04/02/19 07:46,"668 Center St, Seattle, WA 98101"
8,176564,USB-C Charging Cable,1,11.95,04/12/19 10:58,"790 Ridge St, Atlanta, GA 30301"
9,176565,Macbook Pro Laptop,1,1700,04/24/19 10:38,"915 Willow St, San Francisco, CA 94016"

In [3]:
# Spalteninformationen
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18383 entries, 0 to 18382
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order ID          18324 non-null  object
 1   Product           18324 non-null  object
 2   Quantity Ordered  18324 non-null  object
 3   Price Each        18324 non-null  object
 4   Order Date        18324 non-null  object
 5   Purchase Address  18324 non-null  object
dtypes: object(6)
memory usage: 861.8+ KB

In [4]:
# Spalten in die richtigen Datentypen umwandeln
sales_data["Quantity Ordered"] = pd.to_numeric(
    sales_data["Quantity Ordered"], errors="coerce"
)  # Umwandlung in numerisch
sales_data["Price Each"] = pd.to_numeric(
    sales_data["Price Each"], errors="coerce"
)  # Umwandlung in numerisch
sales_data["Order Date"] = pd.to_datetime(
    sales_data["Order Date"], errors="coerce"
)  # Umwandlung in Datumsformat

## Warnung ignorieren (erscheint, weil "Order Date" urpsrünglich nicht einheitlich formatiert ist...
## ...wird im nächsten Kapitel behandelt)
## Order ID besteht zwar aus Zahlen, hat aber keien numerische Bedeutung

C:\Users\dennis\AppData\Local\Temp\ipykernel_3876\674199152.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  sales_data['Order Date'] = pd.to_datetime(sales_data['Order Date'], errors='coerce')             # Umwandlung in Datumsformat

## Aufgabe 1: Entferne alle Zeilen mit fehlenden Werten
Fehlende Werte in irgendeiner Spalte können Analysen verfälschen, daher werden sie entfernt.
Vergleiche die Anzahl der Zeilen vor und nach dem Entfernen und gebe erneut die ersten 10 Zeilen aus.

In [5]:
# Entfernen von Zeilen mit fehlenden Werten
print(f"Anzahl Zeilen vor dem Entfernen von NA`s: {len(sales_data)}")
sales_data.dropna(inplace=True)
print(f"Anzahl der verbleibenden Zeilen nach dem Entfernen: {len(sales_data)}")

Anzahl Zeilen vor dem Entfernen von NA`s: 18383
Anzahl der verbleibenden Zeilen nach dem Entfernen: 18289

In [6]:
sales_data.head(10)

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2.0,11.95,2019-04-19 08:46:00,"917 1st St, Dallas, TX 75001"
2,176559,Bose SoundSport Headphones,1.0,99.99,2019-04-07 22:30:00,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1.0,600.00,2019-04-12 14:38:00,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1.0,11.99,2019-04-12 14:38:00,"669 Spruce St, Los Angeles, CA 90001"
5,176561,Wired Headphones,1.0,11.99,2019-04-30 09:27:00,"333 8th St, Los Angeles, CA 90001"
6,176562,USB-C Charging Cable,1.0,11.95,2019-04-29 13:03:00,"381 Wilson St, San Francisco, CA 94016"
7,176563,Bose SoundSport Headphones,1.0,99.99,2019-04-02 07:46:00,"668 Center St, Seattle, WA 98101"
8,176564,USB-C Charging Cable,1.0,11.95,2019-04-12 10:58:00,"790 Ridge St, Atlanta, GA 30301"
9,176565,Macbook Pro Laptop,1.0,1700.00,2019-04-24 10:38:00,"915 Willow St, San Francisco, CA 94016"
10,176566,Wired Headphones,1.0,11.99,2019-04-08 14:05:00,"83 7th St, Boston, MA 02215"

## Aufgabe 2: Sortiere nach Bestelldatum
Sortiere die Daten chronologisch nach der Spalte "Order Date", um Trends oder Muster leichter erkennen zu können und gebe die ersten 5 und die letzen Zeilen aus.

In [7]:
# Daten nach der Spalte "Order Date" sortieren
sales_data.sort_values(by="Order Date", inplace=True)

In [8]:
sales_data.head(5)

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
1341,177831,Lightning Charging Cable,1.0,14.95,2019-04-01 03:09:00,"914 6th St, San Francisco, CA 94016"
1188,177687,Wired Headphones,1.0,11.99,2019-04-01 04:12:00,"23 Meadow St, San Francisco, CA 94016"
10680,186754,27in FHD Monitor,1.0,149.99,2019-04-01 05:06:00,"824 Chestnut St, San Francisco, CA 94016"
8948,185103,USB-C Charging Cable,1.0,11.95,2019-04-01 05:18:00,"610 Washington St, San Francisco, CA 94016"
15752,191585,20in Monitor,1.0,109.99,2019-04-01 05:58:00,"686 Main St, New York City, NY 10001"

In [9]:
sales_data.tail(5)

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
13947,189854,USB-C Charging Cable,1.0,11.95,2019-05-01 02:09:00,"743 Elm St, Boston, MA 02215"
5322,181645,Apple Airpods Headphones,1.0,150.00,2019-05-01 02:37:00,"514 2nd St, Los Angeles, CA 90001"
2690,179134,Apple Airpods Headphones,1.0,150.00,2019-05-01 02:41:00,"950 Church St, Los Angeles, CA 90001"
439,176978,Apple Airpods Headphones,1.0,150.00,2019-05-01 03:29:00,"589 Lake St, Portland, OR 97035"
18355,194067,iPhone,1.0,700.00,2019-05-01 04:25:00,"291 North St, San Francisco, CA 94016"

## Aufgabe 3: Filtere große Mengen
Filtere alle Einträge, bei denen die Menge größer als 5 ist. Dies ermöglicht eine Analyse von Bestellungen mit hohen Mengen.

In [10]:
# Filtern der Daten, bei denen "Quantity Ordered" > 5 ist
filtered_data = sales_data[sales_data["Quantity Ordered"] > 5]

print("Gefilterte Daten (Menge > 5):")
filtered_data

Gefilterte Daten (Menge > 5):

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
11836,187851,AAA Batteries (4-pack),6.0,2.99,2019-04-12 00:09:00,"350 Wilson St, Boston, MA 02215"
3451,179865,AAA Batteries (4-pack),6.0,2.99,2019-04-14 11:24:00,"83 Willow St, Austin, TX 73301"
9658,185776,AAA Batteries (4-pack),6.0,2.99,2019-04-14 21:18:00,"85 Maple St, San Francisco, CA 94016"
15414,191260,AAA Batteries (4-pack),6.0,2.99,2019-04-17 15:06:00,"843 Cedar St, Los Angeles, CA 90001"
10937,186997,USB-C Charging Cable,6.0,11.95,2019-04-23 21:54:00,"733 Chestnut St, Seattle, WA 98101"
628,177160,AAA Batteries (4-pack),7.0,2.99,2019-04-26 11:37:00,"689 7th St, Dallas, TX 75001"
1348,177838,AAA Batteries (4-pack),6.0,2.99,2019-04-29 00:16:00,"872 Pine St, San Francisco, CA 94016"
7422,183636,AAA Batteries (4-pack),6.0,2.99,2019-04-30 10:28:00,"116 11th St, Boston, MA 02215"

## Aufgabe 4: Sortiere alphabetisch nach Produkt.

In [11]:
# Daten alphabetisch nach der Spalte "Product" sortieren

print("\nDaten sortiert nach Produktnamen:")
sales_data.sort_values(by="Product")

Daten sortiert nach Produktnamen:

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
35,176588,20in Monitor,1.0,109.99,2019-04-02 04:00:00,"765 Cherry St, Seattle, WA 98101"
11829,187844,20in Monitor,1.0,109.99,2019-04-04 21:22:00,"945 10th St, Atlanta, GA 30301"
8030,184223,20in Monitor,1.0,109.99,2019-04-06 13:32:00,"273 4th St, Austin, TX 73301"
14206,190103,20in Monitor,1.0,109.99,2019-04-04 21:20:00,"741 Church St, Dallas, TX 75001"
881,177397,20in Monitor,1.0,109.99,2019-04-27 18:20:00,"438 Park St, Austin, TX 73301"
...,...,...,...,...,...,...
10004,186105,iPhone,1.0,700.00,2019-04-08 14:30:00,"736 12th St, Boston, MA 02215"
16890,192677,iPhone,1.0,700.00,2019-04-08 14:34:00,"75 Main St, Boston, MA 02215"
16817,192609,iPhone,1.0,700.00,2019-04-08 15:45:00,"599 Johnson St, New York City, NY 10001"
6133,182420,iPhone,1.0,700.00,2019-04-08 12:55:00,"253 River St, Atlanta, GA 30301"
18355,194067,iPhone,1.0,700.00,2019-05-01 04:25:00,"291 North St, San Francisco, CA 94016"

## Aufgabe 5: Filtere nach Preisbereich
Filtere alle Einträge, bei denen der Preis zwischen 10 und 100 liegt und sortiere die Daten nach dem Preis. Dies hilft, Bestellungen in einem bestimmten Preisbereich zu analysieren. Welche Produkte liegen in diesem Preisbereich?

In [12]:
# Filtern der Daten, bei denen der Preis zwischen 10 und 100 liegt

price_filtered_data = sales_data[
    (sales_data["Price Each"] >= 10) & (sales_data["Price Each"] <= 100)
]
print("\nGefilterte Daten (Preis zwischen 10 und 100):")
price_filtered_data.sort_values(by="Price Each")  # sortieren

Gefilterte Daten (Preis zwischen 10 und 100):

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
18323,194038,USB-C Charging Cable,1.0,11.95,2019-04-23 09:09:00,"163 Lincoln St, San Francisco, CA 94016"
9834,185945,USB-C Charging Cable,1.0,11.95,2019-04-23 09:15:00,"193 11th St, San Francisco, CA 94016"
12013,188018,USB-C Charging Cable,1.0,11.95,2019-04-23 09:17:00,"898 10th St, Los Angeles, CA 90001"
9705,185822,USB-C Charging Cable,1.0,11.95,2019-04-23 09:18:00,"289 6th St, New York City, NY 10001"
6135,182421,USB-C Charging Cable,1.0,11.95,2019-04-09 12:46:00,"411 Meadow St, New York City, NY 10001"
...,...,...,...,...,...,...
3820,180221,Bose SoundSport Headphones,1.0,99.99,2019-04-01 08:00:00,"789 7th St, Los Angeles, CA 90001"
13773,189688,Bose SoundSport Headphones,1.0,99.99,2019-04-30 22:27:00,"895 14th St, San Francisco, CA 94016"
8084,184275,Bose SoundSport Headphones,1.0,99.99,2019-04-01 10:34:00,"434 12th St, San Francisco, CA 94016"
10204,186297,Bose SoundSport Headphones,1.0,99.99,2019-04-01 07:01:00,"944 Cherry St, Atlanta, GA 30301"
12546,188522,Bose SoundSport Headphones,1.0,99.99,2019-04-01 10:36:00,"534 River St, Los Angeles, CA 90001"

In [13]:
# Übersicht der Produkte
unique_products10to100 = price_filtered_data["Product"].unique()
print(unique_products10to100)

['Lightning Charging Cable' 'Wired Headphones' 'USB-C Charging Cable'
 'Bose SoundSport Headphones']

## Aufgabe 6: Filtere nach Bestelldatum
Filtere alle Bestellungen, die im April 2019 in der ersten Woche getätigt wurden. Dieser Filter ermöglicht die Analyse von Bestellungen in einem bestimmten Zeitraum:

In [14]:
# Filtern der Daten nach Bestellungen, die im April 2019 getätigt wurden

first_week_april = sales_data[
    (sales_data["Order Date"].dt.month == 4) & (sales_data["Order Date"].dt.day <= 7)
]

print("\nGefilterte Daten (1. Aprilwoche 2019):")
first_week_april

Gefilterte Daten (1. Aprilwoche 2019):

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
1341,177831,Lightning Charging Cable,1.0,14.95,2019-04-01 03:09:00,"914 6th St, San Francisco, CA 94016"
1188,177687,Wired Headphones,1.0,11.99,2019-04-01 04:12:00,"23 Meadow St, San Francisco, CA 94016"
10680,186754,27in FHD Monitor,1.0,149.99,2019-04-01 05:06:00,"824 Chestnut St, San Francisco, CA 94016"
8948,185103,USB-C Charging Cable,1.0,11.95,2019-04-01 05:18:00,"610 Washington St, San Francisco, CA 94016"
15752,191585,20in Monitor,1.0,109.99,2019-04-01 05:58:00,"686 Main St, New York City, NY 10001"
...,...,...,...,...,...,...
12695,188661,27in FHD Monitor,1.0,149.99,2019-04-07 23:54:00,"950 Wilson St, Los Angeles, CA 90001"
15321,191170,AA Batteries (4-pack),2.0,3.84,2019-04-07 23:55:00,"763 6th St, Los Angeles, CA 90001"
5234,181558,Apple Airpods Headphones,1.0,150.00,2019-04-07 23:55:00,"755 Elm St, Austin, TX 73301"
4349,180722,USB-C Charging Cable,1.0,11.95,2019-04-07 23:57:00,"268 Lake St, San Francisco, CA 94016"
5288,181612,Lightning Charging Cable,2.0,14.95,2019-04-07 23:58:00,"445 Washington St, Boston, MA 02215"

## Aufgabe 7: Kombiniere Filterbedingungen
Filtere Bestellungen, die in größerer Menge bestellt wurden und einen Preis > 50 enthalten. Dies kombiniert mehrere Bedingungen, um spezifische Bestellungen zu analysieren:

In [15]:
# Filtern der Daten nach Mengenbestellung und Preis > 50
combined_filter_data = sales_data[
    (sales_data["Quantity Ordered"] > 1) & (sales_data["Price Each"] > 50)
]
print("\nGefilterte Daten (Mengenbestellung und Preis > 50):")
combined_filter_data

Gefilterte Daten (Mengenbestellung und Preis > 50):

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
2868,179308,Apple Airpods Headphones,2.0,150.00,2019-04-01 19:47:00,"150 Sunset St, Austin, TX 73301"
13589,189511,Bose SoundSport Headphones,2.0,99.99,2019-04-01 21:47:00,"563 Elm St, Los Angeles, CA 90001"
10798,186866,27in 4K Gaming Monitor,2.0,389.99,2019-04-02 19:29:00,"721 13th St, San Francisco, CA 94016"
16298,192105,34in Ultrawide Monitor,2.0,379.99,2019-04-03 07:06:00,"950 Hill St, San Francisco, CA 94016"
2838,179278,Apple Airpods Headphones,2.0,150.00,2019-04-03 08:18:00,"334 Meadow St, Austin, TX 73301"
607,177139,Apple Airpods Headphones,2.0,150.00,2019-04-03 14:05:00,"723 Madison St, San Francisco, CA 94016"
16315,192122,Bose SoundSport Headphones,2.0,99.99,2019-04-04 14:35:00,"747 Main St, New York City, NY 10001"
10336,186422,20in Monitor,2.0,109.99,2019-04-05 15:22:00,"467 Elm St, New York City, NY 10001"
1377,177866,Apple Airpods Headphones,2.0,150.00,2019-04-06 17:11:00,"855 Main St, Los Angeles, CA 90001"
11977,187982,iPhone,2.0,700.00,2019-04-06 22:03:00,"213 6th St, Atlanta, GA 30301"
160,176710,20in Monitor,2.0,109.99,2019-04-07 10:00:00,"848 West St, Dallas, TX 75001"
3670,180076,Bose SoundSport Headphones,2.0,99.99,2019-04-07 10:53:00,"204 Hill St, Austin, TX 73301"
17839,193578,Flatscreen TV,2.0,300.00,2019-04-08 17:32:00,"375 Jackson St, San Francisco, CA 94016"
7264,183485,Bose SoundSport Headphones,2.0,99.99,2019-04-11 23:50:00,"35 12th St, New York City, NY 10001"
5927,182220,34in Ultrawide Monitor,2.0,379.99,2019-04-14 12:04:00,"587 Dogwood St, San Francisco, CA 94016"
16337,192143,Bose SoundSport Headphones,2.0,99.99,2019-04-14 19:52:00,"81 5th St, San Francisco, CA 94016"
15282,191134,20in Monitor,2.0,109.99,2019-04-16 12:33:00,"617 Sunset St, New York City, NY 10001"
1268,177765,Bose SoundSport Headphones,2.0,99.99,2019-04-16 13:57:00,"528 1st St, New York City, NY 10001"
4740,181090,Apple Airpods Headphones,2.0,150.00,2019-04-17 06:51:00,"22 West St, Los Angeles, CA 90001"
16470,192271,iPhone,2.0,700.00,2019-04-18 17:14:00,"770 14th St, Los Angeles, CA 90001"
266,176809,Bose SoundSport Headphones,2.0,99.99,2019-04-19 01:14:00,"278 13th St, San Francisco, CA 94016"
2351,178806,Apple Airpods Headphones,2.0,150.00,2019-04-21 10:15:00,"881 Jefferson St, New York City, NY 10001"
4005,180397,Apple Airpods Headphones,2.0,150.00,2019-04-21 10:30:00,"757 West St, Los Angeles, CA 90001"
5219,181544,Macbook Pro Laptop,2.0,1700.00,2019-04-22 12:48:00,"731 11th St, New York City, NY 10001"
14666,190543,20in Monitor,2.0,109.99,2019-04-22 16:27:00,"893 Hickory St, Los Angeles, CA 90001"
5672,181982,Apple Airpods Headphones,2.0,150.00,2019-04-22 22:51:00,"162 Washington St, San Francisco, CA 94016"
10301,186389,27in FHD Monitor,2.0,149.99,2019-04-25 11:17:00,"934 Church St, Boston, MA 02215"
13725,189642,Apple Airpods Headphones,2.0,150.00,2019-04-25 12:37:00,"509 Highland St, San Francisco, CA 94016"
3691,180097,20in Monitor,2.0,109.99,2019-04-25 22:40:00,"47 7th St, Seattle, WA 98101"
7865,184065,34in Ultrawide Monitor,2.0,379.99,2019-04-26 10:30:00,"859 14th St, Boston, MA 02215"
4717,181069,Macbook Pro Laptop,2.0,1700.00,2019-04-27 21:01:00,"668 Park St, San Francisco, CA 94016"
6844,183090,Apple Airpods Headphones,2.0,150.00,2019-04-28 11:47:00,"843 Park St, Los Angeles, CA 90001"
16680,192477,27in FHD Monitor,2.0,149.99,2019-04-28 16:39:00,"192 6th St, Austin, TX 73301"
10746,186818,27in FHD Monitor,2.0,149.99,2019-04-28 20:47:00,"283 7th St, Boston, MA 02215"
15670,191507,27in 4K Gaming Monitor,2.0,389.99,2019-04-29 06:39:00,"740 8th St, Seattle, WA 98101"
15706,191541,Bose SoundSport Headphones,2.0,99.99,2019-04-30 12:42:00,"102 Hill St, New York City, NY 10001"