---

![image info](https://user-images.githubusercontent.com/91945811/146929832-e78ff1f4-2739-41b1-acd3-019a39b6a42c.png)

<div style="float: right; font-size: small;">
    Erstellt von Fakher Ahmed für Data Science. Institut by Fabian Rappert
</div>

# Inhaltsverzeichnis 

- **Pandas - Praktische Übung**
    - **1. Aufgabe: Der Datensatz**
    - **2. Aufgabe: Manager & Mitarbeiter**
    - **3. Aufgabe: Männer & Frauen**
    - **4. Aufgabe: Gehaltserhöhung**
    - **5. Aufgabe: Alter & Beschäftigung**

# Pandas - Praktische Übung

In diesem Notebook wollen wir für einen Datensatz (`"Employee-Overview.csv"` - siehe Kursbereich) einige Fragen von Interesse beantworten. Dieser Datensatz enthält die (fiktiven) Mitarbeiterdaten einer (ebenfalls fiktiven) Firma. Benutze im folgenden die Bibliothek `pandas`. 

> <span style="color:red"> **_WICHTIG:_** </span> Der `import` anderer Bibliotheken ist in diesem Notebook nicht notwendig.

In [1]:
import pandas as pd

## 1. Aufgabe: Der Datensatz 

- Lies die csv-Datei `Employee-Overview.csv` in ein `DataFrame` ein. Mache dich mit den Daten vertraut. Beantworte folgende Fragen:

1. Wieviele Mitarbeiter hat das Unternehmen?
2. Wieviele Bereiche (`Dept_Name`) hat das Unternehmen? Wie lauten deren Namen?
3. Wieviele Mitarbeiter arbeiten in den verschiedenen Bereichen?

> <span style="color:blue"> **_INFO:_** </span> Bei letzterer Aufgabe könnte der Befehl [`groupby`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html) helfen.

In [2]:
# Schritt 1: Laden der CSV-Datei in ein DataFrame
# Die CSV-Datei enthält die Mitarbeiterdaten einer fiktiven Firma.
# Sie wird in ein pandas-DataFrame geladen, um sie einfacher analysieren zu können.
file_path = "Data/Employee-Overview.csv"
df = pd.read_csv(file_path)  # CSV-Datei lesen und in ein DataFrame laden

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240124 entries, 0 to 240123
Data columns (total 15 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Mitarbeiter_ID          240124 non-null  int64
 1   MA_Vorname              240124 non-null  object
 2   MA_Nachname             240124 non-null  object
 3   Manager_ID              240124 non-null  int64
 4   MAN_Vorname             240124 non-null  object
 5   MAN_Nachname            240124 non-null  object
 6   Dept_No.                240124 non-null  object
 7   Dept_Name               240124 non-null  object
 8   Beschaeftigung          240124 non-null  object
 9   Mitarbeiter_Gehalt      81635 non-null   float64
 10  Gehaltserhoehung        240124 non-null  object
 11  Titel_Mitarbeiter       240124 non-null  object
 12  Geschlecht_Mitarbeiter  240124 non-null  object
 13  Bday_Mitarbeiter        240124 non-null  object
 14  Hire_Date_Mitarbeiter   240124 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 27.5+ MB

In [4]:
df.head()

,Mitarbeiter_ID,MA_Vorname,MA_Nachname,Manager_ID,MAN_Vorname,MAN_Nachname,Dept_No.,Dept_Name,Beschaeftigung,Mitarbeiter_Gehalt,Gehaltserhoehung,Titel_Mitarbeiter,Geschlecht_Mitarbeiter,Bday_Mitarbeiter,Hire_Date_Mitarbeiter
0,111939,Yuchang,Weedman,111939,Yuchang,Weedman,d009,Customer Service,Führungskraft,58745.0,JA,Manager,M,1960-03-25,1989-07-10
1,111534,Hilary,Kambil,111534,Hilary,Kambil,d008,Research,Führungskraft,79393.0,JA,Manager,F,1952-06-27,1988-01-31
2,110567,Leon,DasSarma,110567,Leon,DasSarma,d005,Development,Führungskraft,74510.0,JA,Manager,F,1964-04-25,1986-10-21
3,111133,Hauke,Zhang,111133,Hauke,Zhang,d007,Sales,Führungskraft,101987.0,NEIN,Manager,M,1955-03-16,1986-12-30
4,110114,Isamu,Legleitner,110114,Isamu,Legleitner,d002,Finance,Führungskraft,83457.0,JA,Manager,F,1957-03-28,1985-01-14

In [5]:
df.describe(include="all")

,Mitarbeiter_ID,MA_Vorname,MA_Nachname,Manager_ID,MAN_Vorname,MAN_Nachname,Dept_No.,Dept_Name,Beschaeftigung,Mitarbeiter_Gehalt,Gehaltserhoehung,Titel_Mitarbeiter,Geschlecht_Mitarbeiter,Bday_Mitarbeiter,Hire_Date_Mitarbeiter
count,240124.000000,240124,240124,240124.000000,240124,240124,240124,240124,240124,81635.000000,240124,240124,240124,240124,240124
unique,NaN,1275,1637,NaN,9,9,9,9,2,NaN,2,7,2,4750,5425
top,NaN,Shahab,Coorg,NaN,Leon,DasSarma,d005,Development,Mitarbeiter,NaN,JA,Senior Engineer,M,1957-02-09,1985-06-06
freq,NaN,241,187,NaN,61386,61386,61386,61386,240115,NaN,228163,85939,144114,79,114
mean,253080.615365,NaN,NaN,110728.878596,NaN,NaN,NaN,NaN,NaN,71964.799927,NaN,NaN,NaN,NaN,NaN
std,161853.087323,NaN,NaN,515.530172,NaN,NaN,NaN,NaN,NaN,17332.125083,NaN,NaN,NaN,NaN,NaN
min,10001.000000,NaN,NaN,110039.000000,NaN,NaN,NaN,NaN,NaN,39012.000000,NaN,NaN,NaN,NaN,NaN
25%,84878.750000,NaN,NaN,110420.000000,NaN,NaN,NaN,NaN,NaN,58976.000000,NaN,NaN,NaN,NaN,NaN
50%,249792.500000,NaN,NaN,110567.000000,NaN,NaN,NaN,NaN,NaN,69766.000000,NaN,NaN,NaN,NaN,NaN
75%,424895.250000,NaN,NaN,111133.000000,NaN,NaN,NaN,NaN,NaN,82537.500000,NaN,NaN,NaN,NaN,NaN
max,499999.000000,NaN,NaN,111939.000000,NaN,NaN,NaN,NaN,NaN,158220.000000,NaN,NaN,NaN,NaN,NaN

Die Spalten sind nicht ideal formatiert. Mitarbeiter_ID sollte beispielsweise keien numerische Spalte sein. Eine ordentliche Formatierung ist für eine schnelle Übersicht sehr hilfsvoll.

In [6]:
# Aufgabe 1: Wie viele Mitarbeiter hat das Unternehmen?

total_employees = df["Mitarbeiter_ID"].nunique()  # Anzahl der Zeilen im DataFrame
print(f"Das Unternehmen hat insgesamt {total_employees} Mitarbeiter.")

# oder so:
# Jede Zeile repräsentiert einen Mitarbeiter, daher ist die Anzahl der Zeilen gleich der Anzahl der Mitarbeiter.
total_employees = len(df)
print(f"\nDas Unternehmen hat insgesamt {total_employees} Mitarbeiter.")

# Aufgabe 2: Wie viele Bereiche (Dept_Name) hat das Unternehmen? Wie lauten deren Namen?
# 1. Die Anzahl der eindeutigen Bereiche (Departments) wird mit `nunique()` ermittelt.
# 2. Die Namen der Bereiche werden mit `unique()` abgerufen, das alle einzigartigen Werte einer Spalte zurückgibt.
unique_departments = df["Dept_Name"].nunique()  # Anzahl der eindeutigen Bereiche
department_names = df["Dept_Name"].unique()  # Namen der Bereiche
print(f"\nDas Unternehmen hat {unique_departments} Bereiche.")
print("Die Namen der Bereiche sind:")
for name in department_names:  # Schleife zum Ausgeben der Namen
    print(f"- {name}")

# Aufgabe 3: Wie viele Mitarbeiter arbeiten in den verschiedenen Bereichen?
# Mit der Methode `groupby('Dept_Name')` werden die Daten nach Bereichen gruppiert.
# `size()` zählt die Anzahl der Zeilen (Mitarbeiter) pro Gruppe (Bereich).
employees_per_department = df.groupby("Dept_Name").size()
print("\nAnzahl der Mitarbeiter pro Bereich:")
for department, count in employees_per_department.items():  # Schleife zur Ausgabe der Ergebnisse
    print(f"- {department}: {count} Mitarbeiter")

Das Unternehmen hat insgesamt 240124 Mitarbeiter.

Das Unternehmen hat insgesamt 240124 Mitarbeiter.

Das Unternehmen hat 9 Bereiche.
Die Namen der Bereiche sind:
- Customer Service
- Research
- Development
- Sales
- Finance
- Human Resources
- Quality Management
- Marketing
- Production

Anzahl der Mitarbeiter pro Bereich:
- Customer Service: 17569 Mitarbeiter
- Development: 61386 Mitarbeiter
- Finance: 12437 Mitarbeiter
- Human Resources: 12898 Mitarbeiter
- Marketing: 14842 Mitarbeiter
- Production: 53304 Mitarbeiter
- Quality Management: 14546 Mitarbeiter
- Research: 15441 Mitarbeiter
- Sales: 37701 Mitarbeiter

## 2. Aufgabe: Manager & Mitarbeiter

- Wie viele Manager gibt es? Finde dazu die Anzahl von `Führungskräften` in der Spalte `Beschaeftigung`. 
- Stelle die Anzahl an `Führungskräften` und `Mitarbeitern` gegenüber.

In [7]:
# Aufgabe 2: Manager und Mitarbeiter analysieren

# Ziel:
# - Finde die Anzahl der Manager (Führungskräfte) in der Spalte 'Beschaeftigung'.
# - Vergleiche die Anzahl der Führungskräfte mit der Anzahl der Mitarbeiter.

# Schritt 1: Gruppierung der Daten nach 'Beschaeftigung'
# Die Spalte 'Beschaeftigung' enthält Informationen darüber, ob eine Person
# eine Führungskraft ('Führungskraft') oder ein normaler Mitarbeiter ('Mitarbeiter') ist.
# Wir verwenden die Methode `value_counts()`, um die Häufigkeiten zu zählen.
employment_counts = df["Beschaeftigung"].value_counts()

# Schritt 2: Anzahl der Führungskräfte und Mitarbeiter extrahieren
# `value_counts` gibt uns die Anzahl für jede Kategorie. Hier filtern wir die Werte heraus.
num_managers = employment_counts.get("Führungskraft", 0)  # Anzahl der Führungskräfte
num_employees = employment_counts.get("Mitarbeiter", 0)  # Anzahl der Mitarbeiter

# Schritt 3: Ergebnisse anzeigen
print(f"Anzahl der Führungskräfte: {num_managers}")
print(f"Anzahl der Mitarbeiter: {num_employees}")

# Schritt 4: Gegenüberstellung der Anzahl
# Berechnung des Anteils der Führungskräfte an der Gesamtanzahl
total_people = num_managers + num_employees  # Gesamtanzahl der Personen
if total_people > 0:  # Vermeidung einer Division durch Null
    manager_percentage = (num_managers / total_people) * 100
    employee_percentage = (num_employees / total_people) * 100
    print(f"Prozentsatz Führungskräfte: {manager_percentage:.4f}%")
    print(f"Prozentsatz Mitarbeiter: {employee_percentage:.4f}%")
else:
    print("Keine Daten zu Führungskräften oder Mitarbeitern vorhanden.")

Anzahl der Führungskräfte: 9
Anzahl der Mitarbeiter: 240115
Prozentsatz Führungskräfte: 0.0037%
Prozentsatz Mitarbeiter: 99.9963%

## 3. Aufgabe: Männer & Frauen

- Stelle das Gehalt der Frauen und Männer gegenüber: Was verdienen Männer im Schnitt? Was Frauen?

In [8]:
if "Geschlecht_Mitarbeiter" in df.columns and "Mitarbeiter_Gehalt" in df.columns:
    df["Mitarbeiter_Gehalt"] = pd.to_numeric(
        df["Mitarbeiter_Gehalt"], errors="coerce"
    )  # Sicherstellen, dass Gehälter numerisch sind

    # Durchschnittsgehalt berechnen
    avg_salary_men = df[df["Geschlecht_Mitarbeiter"] == "M"]["Mitarbeiter_Gehalt"].mean()
    avg_salary_women = df[df["Geschlecht_Mitarbeiter"] == "F"]["Mitarbeiter_Gehalt"].mean()
    print(f"\nDurchschnittsgehalt der Männer: {avg_salary_men:.2f}")
    print(f"Durchschnittsgehalt der Frauen: {avg_salary_women:.2f}")

Durchschnittsgehalt der Männer: 71990.47
Durchschnittsgehalt der Frauen: 71926.40

## 4. Aufgabe: Gehaltserhöhung

- Die Spalte `Gehaltserhoehung` gibt an, ob die Person eine Gehaltserhöhung bekommt. Sollte hier "JA" stehen, berechne einen Aufschlag von 10% auf das aktuelle Gehalt. 

> <span style="color:blue"> **_INFO:_** </span> Der Befehl [`apply`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html) könnte hier helfen. Damit kann man eine Funktion auf _jeden_ Eintrag einer Spalte anwenden.

In [9]:
if "Gehaltserhoehung" in df.columns and "Mitarbeiter_Gehalt" in df.columns:
    df["Mitarbeiter_Gehalt"] = pd.to_numeric(
        df["Mitarbeiter_Gehalt"], errors="coerce"
    )  # Sicherstellen, dass Gehälter numerisch sind

    def calculate_raise(row):
        if row["Gehaltserhoehung"] == "JA":
            return row["Mitarbeiter_Gehalt"] * 1.1  # 10% Aufschlag
        return row["Mitarbeiter_Gehalt"]

    df["Bevorstehendes_Gehalt"] = df.apply(calculate_raise, axis=1)
    print("\nGehälter wurden aktualisiert. Hier sind die ersten Einträge:")
    print(df[["Mitarbeiter_Gehalt", "Gehaltserhoehung", "Bevorstehendes_Gehalt"]].head())

Gehälter wurden aktualisiert. Hier sind die ersten Einträge:
   Mitarbeiter_Gehalt Gehaltserhoehung  Bevorstehendes_Gehalt
0             58745.0               JA                64619.5
1             79393.0               JA                87332.3
2             74510.0               JA                81961.0
3            101987.0             NEIN               101987.0
4             83457.0               JA                91802.7

## 5. Aufgabe: Alter & Beschäftigung

- Wie ist der Name des jüngsten Mitarbeiters des Unternehmens?

- Wer arbeitet am schon am längsten im Unternehmen?

In [10]:
if "Bday_Mitarbeiter" in df.columns:
    df["Bday_Mitarbeiter"] = pd.to_datetime(df["Bday_Mitarbeiter"], errors="coerce")
    jung = df.loc[df["Bday_Mitarbeiter"].idxmax()]
    print(
        f"\nDer jüngste Mitarbeiter ist {jung['MA_Vorname']} {jung['MA_Nachname']}, geboren am {jung['Bday_Mitarbeiter'].date()}."
    )

if "Hire_Date_Mitarbeiter" in df.columns:
    df["Hire_Date_Mitarbeiter"] = pd.to_datetime(df["Hire_Date_Mitarbeiter"], errors="coerce")
    alt = df.loc[df["Hire_Date_Mitarbeiter"].idxmin()]
    print(
        f"\nDer Mitarbeiter mit der längsten Betriebszugehörigkeit ist {alt['MA_Vorname']} {alt['MA_Nachname']}, eingestellt am {alt['Hire_Date_Mitarbeiter'].date()}."
    )

Der jüngste Mitarbeiter ist Zsolt Riefers, geboren am 1965-02-01.

Der Mitarbeiter mit der längsten Betriebszugehörigkeit ist Przemyslawa Kaelbling, eingestellt am 1985-01-01.

Hinweis: Die if Bedingungen sind nur ein nice to have :)

---

## Lösungen zu den Aufgaben mit iloc und loc

In [11]:
# 1. Mit iloc: Gib die ersten 5 Zeilen des DataFrames aus
iloc_aufgabe_1 = df.iloc[:5]
iloc_aufgabe_1

,Mitarbeiter_ID,MA_Vorname,MA_Nachname,Manager_ID,MAN_Vorname,MAN_Nachname,Dept_No.,Dept_Name,Beschaeftigung,Mitarbeiter_Gehalt,Gehaltserhoehung,Titel_Mitarbeiter,Geschlecht_Mitarbeiter,Bday_Mitarbeiter,Hire_Date_Mitarbeiter,Bevorstehendes_Gehalt
0,111939,Yuchang,Weedman,111939,Yuchang,Weedman,d009,Customer Service,Führungskraft,58745.0,JA,Manager,M,1960-03-25,1989-07-10,64619.5
1,111534,Hilary,Kambil,111534,Hilary,Kambil,d008,Research,Führungskraft,79393.0,JA,Manager,F,1952-06-27,1988-01-31,87332.3
2,110567,Leon,DasSarma,110567,Leon,DasSarma,d005,Development,Führungskraft,74510.0,JA,Manager,F,1964-04-25,1986-10-21,81961.0
3,111133,Hauke,Zhang,111133,Hauke,Zhang,d007,Sales,Führungskraft,101987.0,NEIN,Manager,M,1955-03-16,1986-12-30,101987.0
4,110114,Isamu,Legleitner,110114,Isamu,Legleitner,d002,Finance,Führungskraft,83457.0,JA,Manager,F,1957-03-28,1985-01-14,91802.7

In [12]:
# 2. Mit iloc: Zeige nur die 3. Zeile (Index 2)
iloc_aufgabe_2 = df.iloc[2]
iloc_aufgabe_2

Mitarbeiter_ID                         110567
MA_Vorname                               Leon
MA_Nachname                          DasSarma
Manager_ID                             110567
MAN_Vorname                              Leon
MAN_Nachname                         DasSarma
Dept_No.                                 d005
Dept_Name                         Development
Beschaeftigung                  Führungskraft
Mitarbeiter_Gehalt                    74510.0
Gehaltserhoehung                           JA
Titel_Mitarbeiter                     Manager
Geschlecht_Mitarbeiter                      F
Bday_Mitarbeiter          1964-04-25 00:00:00
Hire_Date_Mitarbeiter     1986-10-21 00:00:00
Bevorstehendes_Gehalt                 81961.0
Name: 2, dtype: object

In [13]:
# 3. Mit iloc: Gib den Vor- und Nachnamen des Mitarbeiters in der 10. Zeile aus
iloc_aufgabe_3 = df.iloc[9][["MA_Vorname", "MA_Nachname"]]
iloc_aufgabe_3

MA_Vorname       Chiranjit
MA_Nachname    Attimonelli
Name: 9, dtype: object

In [14]:
# 4. Mit iloc: Zeige die Werte der ersten 3 Zeilen und der Spalten „MA_Vorname“ und „MA_Nachname“
# Dafür holen wir Spalten 1 und 2 (Indexbasiert: 1 = MA_Vorname, 2 = MA_Nachname)
iloc_aufgabe_4 = df.iloc[:3, [1, 2]]
iloc_aufgabe_4

  MA_Vorname MA_Nachname
0    Yuchang     Weedman
1     Hilary      Kambil
2       Leon    DasSarma

In [15]:
# 5. Mit iloc: Gib die letzten 5 Zeilen aus
iloc_aufgabe_5 = df.iloc[-5:]
iloc_aufgabe_5

,Mitarbeiter_ID,MA_Vorname,MA_Nachname,Manager_ID,MAN_Vorname,MAN_Nachname,Dept_No.,Dept_Name,Beschaeftigung,Mitarbeiter_Gehalt,Gehaltserhoehung,Titel_Mitarbeiter,Geschlecht_Mitarbeiter,Bday_Mitarbeiter,Hire_Date_Mitarbeiter,Bevorstehendes_Gehalt
240119,486284,Venkatesan,Peternell,111939,Yuchang,Weedman,d009,Customer Service,Mitarbeiter,NaN,JA,Senior Staff,F,1955-08-29,1985-04-19,NaN
240120,486288,Behnaam,Ritzmann,111939,Yuchang,Weedman,d009,Customer Service,Mitarbeiter,NaN,JA,Staff,F,1954-04-21,1985-05-05,NaN
240121,486303,Chirstian,Ramras,111939,Yuchang,Weedman,d009,Customer Service,Mitarbeiter,NaN,JA,Senior Staff,M,1964-02-20,1988-02-21,NaN
240122,486351,Xuejia,Slutz,111939,Yuchang,Weedman,d009,Customer Service,Mitarbeiter,NaN,JA,Senior Staff,M,1955-03-17,1989-11-13,NaN
240123,486423,Kasidit,Taneja,111939,Yuchang,Weedman,d009,Customer Service,Mitarbeiter,NaN,JA,Senior Staff,F,1954-01-30,1988-11-01,NaN

In [16]:
# 1. Mit loc: Zeige alle Daten für den Mitarbeiter mit der ID 111133
loc_aufgabe_1 = df.loc[df["Mitarbeiter_ID"] == 111133]
loc_aufgabe_1

,Mitarbeiter_ID,MA_Vorname,MA_Nachname,Manager_ID,MAN_Vorname,MAN_Nachname,Dept_No.,Dept_Name,Beschaeftigung,Mitarbeiter_Gehalt,Gehaltserhoehung,Titel_Mitarbeiter,Geschlecht_Mitarbeiter,Bday_Mitarbeiter,Hire_Date_Mitarbeiter,Bevorstehendes_Gehalt
3,111133,Hauke,Zhang,111133,Hauke,Zhang,d007,Sales,Führungskraft,101987.0,NEIN,Manager,M,1955-03-16,1986-12-30,101987.0

In [17]:
# 2. Mit loc: Gib alle weiblichen Führungskräfte aus
loc_aufgabe_2 = df.loc[
    (df["Geschlecht_Mitarbeiter"] == "F") & (df["Beschaeftigung"] == "Führungskraft")
]
loc_aufgabe_2

,Mitarbeiter_ID,MA_Vorname,MA_Nachname,Manager_ID,MAN_Vorname,MAN_Nachname,Dept_No.,Dept_Name,Beschaeftigung,Mitarbeiter_Gehalt,Gehaltserhoehung,Titel_Mitarbeiter,Geschlecht_Mitarbeiter,Bday_Mitarbeiter,Hire_Date_Mitarbeiter,Bevorstehendes_Gehalt
1,111534,Hilary,Kambil,111534,Hilary,Kambil,d008,Research,Führungskraft,79393.0,JA,Manager,F,1952-06-27,1988-01-31,87332.3
2,110567,Leon,DasSarma,110567,Leon,DasSarma,d005,Development,Führungskraft,74510.0,JA,Manager,F,1964-04-25,1986-10-21,81961.0
4,110114,Isamu,Legleitner,110114,Isamu,Legleitner,d002,Finance,Führungskraft,83457.0,JA,Manager,F,1957-03-28,1985-01-14,91802.7
5,110228,Karsten,Sigstam,110228,Karsten,Sigstam,d003,Human Resources,Führungskraft,65400.0,JA,Manager,F,1958-12-02,1985-08-04,71940.0

In [18]:
# 3. Mit loc: Zeige alle Mitarbeiter, die eine Gehaltserhöhung bekommen haben
loc_aufgabe_3 = df.loc[df["Gehaltserhoehung"] == "JA"]
loc_aufgabe_3

,Mitarbeiter_ID,MA_Vorname,MA_Nachname,Manager_ID,MAN_Vorname,MAN_Nachname,Dept_No.,Dept_Name,Beschaeftigung,Mitarbeiter_Gehalt,Gehaltserhoehung,Titel_Mitarbeiter,Geschlecht_Mitarbeiter,Bday_Mitarbeiter,Hire_Date_Mitarbeiter,Bevorstehendes_Gehalt
0,111939,Yuchang,Weedman,111939,Yuchang,Weedman,d009,Customer Service,Führungskraft,58745.0,JA,Manager,M,1960-03-25,1989-07-10,64619.5
1,111534,Hilary,Kambil,111534,Hilary,Kambil,d008,Research,Führungskraft,79393.0,JA,Manager,F,1952-06-27,1988-01-31,87332.3
2,110567,Leon,DasSarma,110567,Leon,DasSarma,d005,Development,Führungskraft,74510.0,JA,Manager,F,1964-04-25,1986-10-21,81961.0
4,110114,Isamu,Legleitner,110114,Isamu,Legleitner,d002,Finance,Führungskraft,83457.0,JA,Manager,F,1957-03-28,1985-01-14,91802.7
5,110228,Karsten,Sigstam,110228,Karsten,Sigstam,d003,Human Resources,Führungskraft,65400.0,JA,Manager,F,1958-12-02,1985-08-04,71940.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240119,486284,Venkatesan,Peternell,111939,Yuchang,Weedman,d009,Customer Service,Mitarbeiter,NaN,JA,Senior Staff,F,1955-08-29,1985-04-19,NaN
240120,486288,Behnaam,Ritzmann,111939,Yuchang,Weedman,d009,Customer Service,Mitarbeiter,NaN,JA,Staff,F,1954-04-21,1985-05-05,NaN
240121,486303,Chirstian,Ramras,111939,Yuchang,Weedman,d009,Customer Service,Mitarbeiter,NaN,JA,Senior Staff,M,1964-02-20,1988-02-21,NaN
240122,486351,Xuejia,Slutz,111939,Yuchang,Weedman,d009,Customer Service,Mitarbeiter,NaN,JA,Senior Staff,M,1955-03-17,1989-11-13,NaN
240123,486423,Kasidit,Taneja,111939,Yuchang,Weedman,d009,Customer Service,Mitarbeiter,NaN,JA,Senior Staff,F,1954-01-30,1988-11-01,NaN

In [19]:
# 4. Mit loc: Liste alle Mitarbeiter*innen im Department „Development“ mit Vor-, Nachnamen und Gehalt
loc_aufgabe_4 = df.loc[
    df["Dept_Name"] == "Development", ["MA_Vorname", "MA_Nachname", "Mitarbeiter_Gehalt"]
]
loc_aufgabe_4

        MA_Vorname    MA_Nachname  Mitarbeiter_Gehalt
2             Leon       DasSarma             74510.0
103560    Tokuyasu  Schiettecatte             88153.0
103566       Emdad        Tiemann             70803.0
103572      Shahab       Figueira             48394.0
103578     Kwangho      Besselaar             65156.0
...            ...            ...                 ...
240110       Rance         Varman             68418.0
240112      Golgen       Lagarias             76363.0
240114      Pranay       Brandsma             49921.0
240116      Dmitry      Kawashimo             76215.0
240118  Ramachenga        Cullers             75046.0

[61386 rows x 3 columns]

In [20]:
# 5. Mit loc: Gib das Geburtsdatum und das Einstellungsdatum von „Isamu Legleitner“ aus
loc_aufgabe_5 = df.loc[
    (df["MA_Vorname"] == "Isamu") & (df["MA_Nachname"] == "Legleitner"),
    ["Bday_Mitarbeiter", "Hire_Date_Mitarbeiter"],
]
loc_aufgabe_5

  Bday_Mitarbeiter Hire_Date_Mitarbeiter
4       1957-03-28            1985-01-14