![image info](https://user-images.githubusercontent.com/91945811/146929832-e78ff1f4-2739-41b1-acd3-019a39b6a42c.png)

## Datenbereinigung

In [1]:
import pandas as pd

In [2]:
# Daten laden
file_path = "sales_data/dirtyData.csv"
df = pd.read_csv(file_path)
print("Originaldaten:")
display(df)

Originaldaten:

,Kunden-ID,Name,Alter,E-Mail-Adresse,Registrierungsdatum,Kaufbetrag,Wohnort
0,1,Anna,25.0,anna@example.com,15.01.2023,"300,5",Berlin
1,2,BOB,26.0,bob(at)example.com,15-01-2023,450.00,Hamburg
2,3,Clara,NaN,clara@example,2023/02/15,220.75,München
3,4,Dave,30.0,dave@example.com,15.03.2023,NaN,koeln
4,5,ANNA,25.0,anna@example.com,15.01.2023,"300,5",berlin
5,6,Petra,29.0,petra@beispiel.de,2023.02.20,"450,00",Frankfurt am Main
6,7,Franz,NaN,franz(at)beispiel.de,01-03-2023,"1.000,50",düsseldorf
7,8,Sophie,NaN,NaN,03.2023,NaN,STUTTGART
8,9,Paul,31.0,paul@example.de,2023-03-15,320.5,berLin
9,10,Lena,28.0,lena(at)beispiel.com,"15,02,2023",NaN,Munich

### Spaltennamen vereinheitlichen
Aufgabe: Vereinheitliche die Spaltennamen (z.B. klein schreiben, Leerzeichen entfernen)

In [3]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_").str.replace("-", "_")

print("\nSpaltennamen vereinheitlicht:")

display(df)

Spaltennamen vereinheitlicht:

,kunden_id,name,alter,e_mail_adresse,registrierungsdatum,kaufbetrag,wohnort
0,1,Anna,25.0,anna@example.com,15.01.2023,"300,5",Berlin
1,2,BOB,26.0,bob(at)example.com,15-01-2023,450.00,Hamburg
2,3,Clara,NaN,clara@example,2023/02/15,220.75,München
3,4,Dave,30.0,dave@example.com,15.03.2023,NaN,koeln
4,5,ANNA,25.0,anna@example.com,15.01.2023,"300,5",berlin
5,6,Petra,29.0,petra@beispiel.de,2023.02.20,"450,00",Frankfurt am Main
6,7,Franz,NaN,franz(at)beispiel.de,01-03-2023,"1.000,50",düsseldorf
7,8,Sophie,NaN,NaN,03.2023,NaN,STUTTGART
8,9,Paul,31.0,paul@example.de,2023-03-15,320.5,berLin
9,10,Lena,28.0,lena(at)beispiel.com,"15,02,2023",NaN,Munich

### Spaltennamen gezielt ändern

In [4]:
df = df.rename(columns={"e_mail_adresse": "email"})

# Überprüfen, ob der Spaltenname geändert wurde
print(df.columns)

Index(['kunden_id', 'name', 'alter', 'email', 'registrierungsdatum',
       'kaufbetrag', 'wohnort'],
      dtype='object')

### Datenübersicht

Wir schauen uns die Spaltenformate und Anzahl der Einträge an

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   kunden_id            10 non-null     int64
 1   name                 10 non-null     object
 2   alter                7 non-null      float64
 3   email                9 non-null      object
 4   registrierungsdatum  10 non-null     object
 5   kaufbetrag           7 non-null      object
 6   wohnort              10 non-null     object
dtypes: float64(1), int64(1), object(5)
memory usage: 692.0+ bytes

In [6]:
# Datenübersicht mittels display
display(df.describe(include="all"))

,kunden_id,name,alter,email,registrierungsdatum,kaufbetrag,wohnort
count,10.00000,10,7.000000,9,10,7,10
unique,NaN,10,NaN,8,9,6,10
top,NaN,Anna,NaN,anna@example.com,15.01.2023,"300,5",Berlin
freq,NaN,1,NaN,2,2,2,1
mean,5.50000,NaN,27.714286,NaN,NaN,NaN,NaN
std,3.02765,NaN,2.429972,NaN,NaN,NaN,NaN
min,1.00000,NaN,25.000000,NaN,NaN,NaN,NaN
25%,3.25000,NaN,25.500000,NaN,NaN,NaN,NaN
50%,5.50000,NaN,28.000000,NaN,NaN,NaN,NaN
75%,7.75000,NaN,29.500000,NaN,NaN,NaN,NaN
max,10.00000,NaN,31.000000,NaN,NaN,NaN,NaN

### Fehlende Werte 
Aufgabe: Identifiziere fehlende Werte

In [7]:
print("\nFehlende Werte pro Spalte:")
print(df.isnull().sum())

Fehlende Werte pro Spalte:
kunden_id              0
name                   0
alter                  3
email                  1
registrierungsdatum    0
kaufbetrag             3
wohnort                0
dtype: int64

In [8]:
display(df)

,kunden_id,name,alter,email,registrierungsdatum,kaufbetrag,wohnort
0,1,Anna,25.0,anna@example.com,15.01.2023,"300,5",Berlin
1,2,BOB,26.0,bob(at)example.com,15-01-2023,450.00,Hamburg
2,3,Clara,NaN,clara@example,2023/02/15,220.75,München
3,4,Dave,30.0,dave@example.com,15.03.2023,NaN,koeln
4,5,ANNA,25.0,anna@example.com,15.01.2023,"300,5",berlin
5,6,Petra,29.0,petra@beispiel.de,2023.02.20,"450,00",Frankfurt am Main
6,7,Franz,NaN,franz(at)beispiel.de,01-03-2023,"1.000,50",düsseldorf
7,8,Sophie,NaN,NaN,03.2023,NaN,STUTTGART
8,9,Paul,31.0,paul@example.de,2023-03-15,320.5,berLin
9,10,Lena,28.0,lena(at)beispiel.com,"15,02,2023",NaN,Munich

In [9]:
# Alterswerte behandeln
df["alter"] = df["alter"].fillna(df["alter"].median())  # Median verwenden

In [10]:
display(df)

,kunden_id,name,alter,email,registrierungsdatum,kaufbetrag,wohnort
0,1,Anna,25.0,anna@example.com,15.01.2023,"300,5",Berlin
1,2,BOB,26.0,bob(at)example.com,15-01-2023,450.00,Hamburg
2,3,Clara,28.0,clara@example,2023/02/15,220.75,München
3,4,Dave,30.0,dave@example.com,15.03.2023,NaN,koeln
4,5,ANNA,25.0,anna@example.com,15.01.2023,"300,5",berlin
5,6,Petra,29.0,petra@beispiel.de,2023.02.20,"450,00",Frankfurt am Main
6,7,Franz,28.0,franz(at)beispiel.de,01-03-2023,"1.000,50",düsseldorf
7,8,Sophie,28.0,NaN,03.2023,NaN,STUTTGART
8,9,Paul,31.0,paul@example.de,2023-03-15,320.5,berLin
9,10,Lena,28.0,lena(at)beispiel.com,"15,02,2023",NaN,Munich

### Zahlen korrigieren

Kaufbeträge korrigieren: Punkte und Kommas vereinheitlichen

In [11]:
df["kaufbetrag"] = df["kaufbetrag"].astype(str).str.replace(",", ".")
display(df)

,kunden_id,name,alter,email,registrierungsdatum,kaufbetrag,wohnort
0,1,Anna,25.0,anna@example.com,15.01.2023,300.5,Berlin
1,2,BOB,26.0,bob(at)example.com,15-01-2023,450.00,Hamburg
2,3,Clara,28.0,clara@example,2023/02/15,220.75,München
3,4,Dave,30.0,dave@example.com,15.03.2023,nan,koeln
4,5,ANNA,25.0,anna@example.com,15.01.2023,300.5,berlin
5,6,Petra,29.0,petra@beispiel.de,2023.02.20,450.00,Frankfurt am Main
6,7,Franz,28.0,franz(at)beispiel.de,01-03-2023,1.000.50,düsseldorf
7,8,Sophie,28.0,NaN,03.2023,nan,STUTTGART
8,9,Paul,31.0,paul@example.de,2023-03-15,320.5,berLin
9,10,Lena,28.0,lena(at)beispiel.com,"15,02,2023",nan,Munich

In [12]:
# Tausender Punkt entfernen mit Regex
df["kaufbetrag"] = df["kaufbetrag"].str.replace(r"(?<=\d)\.(?=\d{3})", "", regex=True)

# Spalte in numerische umwandeln
df["kaufbetrag"] = pd.to_numeric(df["kaufbetrag"], errors="coerce")
display(df)

,kunden_id,name,alter,email,registrierungsdatum,kaufbetrag,wohnort
0,1,Anna,25.0,anna@example.com,15.01.2023,300.50,Berlin
1,2,BOB,26.0,bob(at)example.com,15-01-2023,450.00,Hamburg
2,3,Clara,28.0,clara@example,2023/02/15,220.75,München
3,4,Dave,30.0,dave@example.com,15.03.2023,NaN,koeln
4,5,ANNA,25.0,anna@example.com,15.01.2023,300.50,berlin
5,6,Petra,29.0,petra@beispiel.de,2023.02.20,450.00,Frankfurt am Main
6,7,Franz,28.0,franz(at)beispiel.de,01-03-2023,1000.50,düsseldorf
7,8,Sophie,28.0,NaN,03.2023,NaN,STUTTGART
8,9,Paul,31.0,paul@example.de,2023-03-15,320.50,berLin
9,10,Lena,28.0,lena(at)beispiel.com,"15,02,2023",NaN,Munich

### String-Funktionen anwenden

In [13]:
# Aufgabe: Bereinige und vereinheitliche den Text
df["name"] = df["name"].str.strip().str.capitalize()
df["wohnort"] = df["wohnort"].str.strip().str.capitalize()
display(df)

,kunden_id,name,alter,email,registrierungsdatum,kaufbetrag,wohnort
0,1,Anna,25.0,anna@example.com,15.01.2023,300.50,Berlin
1,2,Bob,26.0,bob(at)example.com,15-01-2023,450.00,Hamburg
2,3,Clara,28.0,clara@example,2023/02/15,220.75,München
3,4,Dave,30.0,dave@example.com,15.03.2023,NaN,Koeln
4,5,Anna,25.0,anna@example.com,15.01.2023,300.50,Berlin
5,6,Petra,29.0,petra@beispiel.de,2023.02.20,450.00,Frankfurt am main
6,7,Franz,28.0,franz(at)beispiel.de,01-03-2023,1000.50,Düsseldorf
7,8,Sophie,28.0,NaN,03.2023,NaN,Stuttgart
8,9,Paul,31.0,paul@example.de,2023-03-15,320.50,Berlin
9,10,Lena,28.0,lena(at)beispiel.com,"15,02,2023",NaN,Munich

### Duplikate entfernen
Aufgabe: Überprüfe und entferne doppelte Datensätze

In [14]:
print(
    "\nAnzahl Duplikate vor Entfernung:",
    df.duplicated(subset=["name", "kaufbetrag", "registrierungsdatum"]).sum(),
)
df = df.drop_duplicates(subset=["name", "kaufbetrag", "registrierungsdatum"])
print(
    "Anzahl Duplikate nach Entfernung:",
    df.duplicated(subset=["name", "kaufbetrag", "registrierungsdatum"]).sum(),
)

Anzahl Duplikate vor Entfernung: 1
Anzahl Duplikate nach Entfernung: 0

### Datumskorrekturen
Aufgabe: Konvertiere das Datum ins richtige Format

In [ ]:
df["registrierungsdatum"] = (
    df["registrierungsdatum"].str.replace("-", ".").str.replace(",", ".").str.replace("/", ".")
)

In [16]:
# Funktion zum Bereinigen der Datumsformate
def parse_date(date):
    formats = ["%Y.%m.%d", "%d.%m.%Y", "%m.%Y"]  # Liste möglicher Formate
    for fmt in formats:
        try:
            return pd.to_datetime(date, format=fmt)
        except ValueError:
            continue
    return pd.NaT  # Wenn kein Format passt, NaT zurückgeben


# Anwenden der Funktion auf die Spalte
df["registrierungsdatum"] = df["registrierungsdatum"].apply(parse_date)

display(df)

,kunden_id,name,alter,email,registrierungsdatum,kaufbetrag,wohnort
0,1,Anna,25.0,anna@example.com,2023-01-15,300.50,Berlin
1,2,Bob,26.0,bob(at)example.com,2023-01-15,450.00,Hamburg
2,3,Clara,28.0,clara@example,2023-02-15,220.75,München
3,4,Dave,30.0,dave@example.com,2023-03-15,NaN,Koeln
5,6,Petra,29.0,petra@beispiel.de,2023-02-20,450.00,Frankfurt am main
6,7,Franz,28.0,franz(at)beispiel.de,2023-03-01,1000.50,Düsseldorf
7,8,Sophie,28.0,NaN,2023-03-01,NaN,Stuttgart
8,9,Paul,31.0,paul@example.de,2023-03-15,320.50,Berlin
9,10,Lena,28.0,lena(at)beispiel.com,2023-02-15,NaN,Munich

In [ ]:
df["email"] = df["email"].str.replace("(at)", "@")
display(df)

,kunden_id,name,alter,email,registrierungsdatum,kaufbetrag,wohnort
0,1,Anna,25.0,anna@example.com,2023-01-15,300.50,Berlin
1,2,Bob,26.0,bob@example.com,2023-01-15,450.00,Hamburg
2,3,Clara,28.0,clara@example,2023-02-15,220.75,München
3,4,Dave,30.0,dave@example.com,2023-03-15,NaN,Koeln
5,6,Petra,29.0,petra@beispiel.de,2023-02-20,450.00,Frankfurt am main
6,7,Franz,28.0,franz@beispiel.de,2023-03-01,1000.50,Düsseldorf
7,8,Sophie,28.0,NaN,2023-03-01,NaN,Stuttgart
8,9,Paul,31.0,paul@example.de,2023-03-15,320.50,Berlin
9,10,Lena,28.0,lena@beispiel.com,2023-02-15,NaN,Munich

In [18]:
### Spalte korrigieren mit einem Dictionary

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Abteilung": ["HR", "Financ", "IT", "HR", "Fin"],
}

df = pd.DataFrame(data)
display(df)

      Name Abteilung
0    Alice        HR
1      Bob    Financ
2  Charlie        IT
3    David        HR
4      Eva       Fin

In [19]:
# Korrektur-Dictionary
korrektur_dict = {
    "Financ": "Finance",
    "Fin": "Finance",
    "HR": "Human Resources",
    "IT": "Information Technology",
}

# Korrigieren der Spalte 'Abteilung' mit replace
df["Korrigierte_Abteilung"] = df["Abteilung"].replace(korrektur_dict)

# Ausgabe des korrigierten DataFrames
display(df)

      Name Abteilung   Korrigierte_Abteilung
0    Alice        HR         Human Resources
1      Bob    Financ                 Finance
2  Charlie        IT  Information Technology
3    David        HR         Human Resources
4      Eva       Fin                 Finance

Die Methode `.str.replace()` unterscheidet sich von `.replace()` in Pandas, da sie auf Zeichenkettenoperationen (Strings) spezialisiert ist. Sie wird verwendet, um **Teile von Zeichenketten** innerhalb einer Spalte (oder Serie) zu ersetzen, während `.replace()` zum **Ersetzen ganzer Werte** (egal welcher Datentyp) im DataFrame oder in einer Spalte dient.

Hier sind die Hauptunterschiede:

---

### **1. `.replace()`**
- Funktioniert auf dem gesamten DataFrame oder einer Serie.
- Kann ganze Werte (nicht nur Strings) ersetzen.
- Unterstützt die Verwendung von Dictionaries oder Listen.
- Eignet sich für das Ersetzen von **kompletten Übereinstimmungen**.

**Beispiel mit `.replace()`:**

In [20]:
df = pd.DataFrame({"Abteilung": ["HR", "Finance", "Financ", "IT"]})

# Ersetzen kompletter Werte
df["Abteilung_korrigiert"] = df["Abteilung"].replace(
    {"Financ": "Finance", "IT": "Information Technology"}
)
print(df)

  Abteilung    Abteilung_korrigiert
0        HR                      HR
1   Finance                 Finance
2    Financ                 Finance
3        IT  Information Technology

---

### **2. `.str.replace()`**
- Funktioniert nur auf textbasierten Daten (Strings).
- Ersetzt Teile von Zeichenketten basierend auf einem Suchmuster (Reguläre Ausdrücke sind möglich).
- Eignet sich für das **teilweise Ersetzen** von Zeichen in Strings.

**Beispiel mit `.str.replace()`:**

In [21]:
df = pd.DataFrame({"Abteilung": ["HR", "Finance", "Financ", "IT"]})

# Ersetzen von Teilen der Zeichenkette
df["Abteilung_korrigiert"] = df["Abteilung"].str.replace("Financ", "Finance")
print(df)

  Abteilung Abteilung_korrigiert
0        HR                   HR
1   Finance             Financee
2    Financ              Finance
3        IT                   IT

Hier wird **nur "Financ" als Teil des Strings ersetzt**, ohne dass andere Werte geändert werden.

---

### **Vergleich anhand eines Beispiels**

**Datensatz:**

In [22]:
data = {"Abteilung": ["HR", "Financ", "Finanzen", "IT"]}
df = pd.DataFrame(data)

1. **Mit `.replace()`:**

In [23]:
df["Abteilung_korrigiert"] = df["Abteilung"].replace({"Financ": "Finance"})

- Ersetzt nur komplette Übereinstimmungen (`"Financ" → "Finance"`).
- `"Finanzen"` bleibt unverändert.

2. **Mit `.str.replace()`:**

In [24]:
df["Abteilung_korrigiert"] = df["Abteilung"].str.replace("Financ", "Finance")

- Ersetzt **Teile von Zeichenketten**, also auch `"Finanzen"` wird angepasst.

---

### Fazit:
- Verwende `.replace()` für **komplette Werteersetzungen**.
- Verwende `.str.replace()` für **Teilersetzungen** innerhalb von Zeichenketten.