![image info](https://user-images.githubusercontent.com/91945811/146929832-e78ff1f4-2739-41b1-acd3-019a39b6a42c.png)

<div style="float: right; font-size: small;">
    Erstellt von Fakher Ahmed für Data Science Institut by Fabian Rappert
</div>

# Pandas Tutorial: concat, merge und join
In diesem Tutorial lernst du, wie man Datenframes kombiniert, und welche Optionen Pandas dabei bietet.

In [3]:
import pandas as pd

# Beispiel-Daten erstellen
df1 = pd.DataFrame({"ID": [1, 2, 3], "Name": ["Anna", "Ben", "Clara"]})

df2 = pd.DataFrame({"ID": [4, 5, 6], "Name": ["David", "Ella", "Finn"]})

df3 = pd.DataFrame({"ID": [1, 2, 4], "Alter": [24, 27, 35]})

print("Datenframe 1:")
display(df1)

print("Datenframe 2:")
display(df2)

print("Datenframe 3:")
display(df3)

Datenframe 1:

   ID   Name
0   1   Anna
1   2    Ben
2   3  Clara

Datenframe 2:

   ID   Name
0   4  David
1   5   Ella
2   6   Finn

Datenframe 3:

   ID  Alter
0   1     24
1   2     27
2   4     35

### **1. Verketten von Datenframes: `concat`**

#### **Grundlagen**
Die Funktion `concat` wird verwendet, um Datenframes entlang einer Achse (`axis`) zu verbinden:
- `axis=0`: Zeilenweise Verkettung (Datenframes untereinander).
- `axis=1`: Spaltenweise Verkettung (Datenframes nebeneinander).

In [5]:
# Zeilenweise Verkettung (Standard)
df_concat = pd.concat([df1, df2], axis=0)
print("Concat - Zeilenweise:")
display(df_concat)

# Spaltenweise Verkettung
df_concat_columns = pd.concat([df1, df3], axis=1)
print("Concat - Spaltenweise:")
display(df_concat_columns)

Concat - Zeilenweise:

   ID   Name
0   1   Anna
1   2    Ben
2   3  Clara
0   4  David
1   5   Ella
2   6   Finn

Concat - Spaltenweise:

   ID   Name  ID  Alter
0   1   Anna   1     24
1   2    Ben   2     27
2   3  Clara   4     35

#### **Wichtige Parameter**
- **`ignore_index`**: Ignoriert den bestehenden Index und erstellt einen neuen (nützlich bei `axis=0`).
- **`keys`**: Fügt Ebenen hinzu, um die Herkunft der Daten zu markieren (MultiIndex).
- **`sort`**: Sortiert die Spalten, wenn Spalten nicht übereinstimmen (Standard: `False`).

In [7]:
# Beispiel: concat mit ignore_index
df_concat_ignore = pd.concat([df1, df2], axis=0, ignore_index=True)
print("Concat - Mit ignore_index:")
display(df_concat_ignore)

# Beispiel: concat mit keys
df_concat_keys = pd.concat([df1, df2], axis=0, keys=["DF1", "DF2"])
print("Concat - Mit keys:")
display(df_concat_keys)

Concat - Mit ignore_index:

   ID   Name
0   1   Anna
1   2    Ben
2   3  Clara
3   4  David
4   5   Ella
5   6   Finn

Concat - Mit keys:

       ID   Name
DF1 0   1   Anna
    1   2    Ben
    2   3  Clara
DF2 0   4  David
    1   5   Ella
    2   6   Finn

In Pandas bietet das Argument `keys` in der `concat`-Funktion mehrere Vorteile, insbesondere wenn du mehrere DataFrames kombinierst. Hier sind die wichtigsten Vorteile:
- **Einen MultiIndex zu erzeugen** und damit Struktur in die Daten zu bringen.
- **Eindeutige Identifizierungen** für zusammengefügte DataFrames zu schaffen.
- **Indexkonflikte zu vermeiden**.
- **Daten leicht zu selektieren und weiterzuverarbeiten**.

Wenn du mit mehreren DataFrames arbeitest und die Herkunft der Daten erhalten bleiben soll, ist `keys` eine sehr sinnvolle Option! 🚀

### **2. Zusammenführen von Datenframes: `merge`**

#### **Grundlagen**
`merge` kombiniert Datenframes basierend auf gemeinsamen Spalten oder Indizes. Es ist ähnlich wie ein SQL-Join.

In [10]:
# Inner Join (Standard)
df_merge_inner = pd.merge(df1, df3, on="ID")
print("Merge - Inner Join:")
display(df_merge_inner)

Merge - Inner Join:

   ID  Name  Alter
0   1  Anna     24
1   2   Ben     27

---

#### **Join-Arten in merge**
- **`inner` (Standard)**: Nur Datensätze, die in beiden Datenframes vorhanden sind.
- **`left`**: Behalte alle Datensätze aus dem linken Datenframe, auch wenn keine Übereinstimmung im rechten Datenframe vorhanden ist.
- **`right`**: Behalte alle Datensätze aus dem rechten Datenframe, auch wenn keine Übereinstimmung im linken Datenframe vorhanden ist.
- **`outer`**: Behalte alle Datensätze aus beiden Datenframes. Fehlende Werte werden mit `NaN` aufgefüllt.

In [12]:
# Left Join
df_merge_left = pd.merge(df1, df3, on="ID", how="left")
print("Merge - Left Join:")
display(df_merge_left)

# Right Join
df_merge_right = pd.merge(df1, df3, on="ID", how="right")
print("Merge - Right Join:")
display(df_merge_right)

# Outer Join
df_merge_outer = pd.merge(df1, df3, on="ID", how="outer")
print("Merge - Outer Join:")
display(df_merge_outer)

Merge - Left Join:

   ID   Name  Alter
0   1   Anna   24.0
1   2    Ben   27.0
2   3  Clara    NaN

Merge - Right Join:

   ID  Name  Alter
0   1  Anna     24
1   2   Ben     27
2   4   NaN     35

Merge - Outer Join:

   ID   Name  Alter
0   1   Anna   24.0
1   2    Ben   27.0
2   3  Clara    NaN
3   4    NaN   35.0

#### **Wichtige Parameter**
- **`on`**: Gibt die gemeinsame Spalte(n) an, auf denen der Join basieren soll.
- **`left_on` / `right_on`**: Unterschiedliche Spaltennamen in den Datenframes können mit diesen Parametern angegeben werden.
- **`suffixes`**: Fügt Suffixe hinzu, wenn Spaltennamen in beiden Datenframes gleich sind (z. B. `_x` und `_y`).

In [14]:
# Beispiel: Unterschiedliche Spaltennamen
df4 = pd.DataFrame({"KundenID": [1, 2, 4], "Alter": [24, 27, 35]})

df_merge_custom = pd.merge(df1, df4, left_on="ID", right_on="KundenID", how="inner")
print("Merge mit unterschiedlichen Spaltennamen:")
display(df_merge_custom)

# Beispiel: Suffixe
df5 = pd.DataFrame({"ID": [1, 2, 3], "Name": ["Alice", "Bob", "Charlie"]})

df_merge_suffixes = pd.merge(df1, df5, on="ID", suffixes=("_df1", "_df5"))
print("Merge mit Suffixen:")
display(df_merge_suffixes)

Merge mit unterschiedlichen Spaltennamen:

   ID  Name  KundenID  Alter
0   1  Anna         1     24
1   2   Ben         2     27

Merge mit Suffixen:

   ID Name_df1 Name_df5
0   1     Anna    Alice
1   2      Ben      Bob
2   3    Clara  Charlie

---

### **3. Verknüpfen basierend auf dem Index: `join`**

#### **Grundlagen**
`join` wird verwendet, um Datenframes basierend auf ihrem Index zu kombinieren. Es ist besonders nützlich, wenn die Datenframes bereits Indizes haben.

In [17]:
# Beispiel-Datenframes mit Index erstellen
df4 = df1.set_index("ID")
df5 = df3.set_index("ID")

print("Datenframe 4 (Index):")
display(df4)

print("Datenframe 5 (Index):")
display(df5)

# Join der Datenframes
df_join = df4.join(df5, how="inner")
print("Join - Inner:")
display(df_join)

Datenframe 4 (Index):

     Name
ID
1    Anna
2     Ben
3   Clara

Datenframe 5 (Index):

    Alter
ID
1      24
2      27
4      35

Join - Inner:

    Name  Alter
ID
1   Anna     24
2    Ben     27

---

#### **Join-Arten in join**
- **`inner` (Standard)**: Nur Datensätze, die in beiden Datenframes vorkommen.
- **`left`**: Behalte alle Datensätze aus dem linken Datenframe.
- **`right`**: Behalte alle Datensätze aus dem rechten Datenframe.
- **`outer`**: Behalte alle Datensätze aus beiden Datenframes.

In [19]:
# Left Join
df_join_left = df4.join(df5, how="left")
print("Join - Left:")
display(df_join_left)

# Right Join
df_join_right = df4.join(df5, how="right")
print("Join - Right:")
display(df_join_right)

# Outer Join
df_join_outer = df4.join(df5, how="outer")
print("Join - Outer:")
display(df_join_outer)

Join - Left:

     Name  Alter
ID
1    Anna   24.0
2     Ben   27.0
3   Clara    NaN

Join - Right:

    Name  Alter
ID
1   Anna     24
2    Ben     27
4    NaN     35

Join - Outer:

     Name  Alter
ID
1    Anna   24.0
2     Ben   27.0
3   Clara    NaN
4     NaN   35.0

---

#### **Wichtige Parameter**
- **`on`**: Gibt den Index an, auf dem der Join basieren soll.
- **`lsuffix` / `rsuffix`**: Fügt Suffixe für Spalten mit denselben Namen hinzu.

```python

In [21]:
# Beispiel: Suffixe in join
df6 = pd.DataFrame({"ID": [1, 2, 3], "Name": ["Alice", "Bob", "Charlie"]}).set_index("ID")

df_join_suffix = df4.join(df6, lsuffix="_df4", rsuffix="_df6")
print("Join mit Suffixen:")
display(df_join_suffix)

Join mit Suffixen:

   Name_df4 Name_df6
ID
1      Anna    Alice
2       Ben      Bob
3     Clara  Charlie


---

### Zusammenfassung und weitere Funktionen

| **Funktion**                 | **Erklärung**                                                                                  | **Anwendung**                                                                                 |
|-------------------------------|-----------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------|
| `concat()`                   | Kombiniert mehrere `Series`- oder `DataFrame`-Objekte entlang eines Indexes oder einer Spalte. | Zusammenführen von Datenquellen mit ähnlicher Struktur, z. B. Monatsberichte.                |
| `DataFrame.join()`           | Kombiniert `DataFrame`-Objekte entlang der Spalten basierend auf einem gemeinsamen Index.      | Zusammenführen von Daten mit gemeinsamen Indizes, z. B. Demografie- und Verkaufsdaten.       |
| `DataFrame.combine_first()`  | Füllt fehlende Werte in einem `DataFrame` mit Werten aus einem anderen `DataFrame`.            | Ergänzen fehlender Daten in einer Haupttabelle mit Hilfstabelleninformationen.               |
| `merge()`                    | Kombiniert zwei Objekte mit SQL-ähnlichen Joins (inner, outer, left, right).                  | Verknüpfen von Daten über gemeinsame Schlüssel, z. B. Kunden-ID.                            |
| `merge_ordered()`            | Kombiniert Objekte entlang einer geordneten Achse und bewahrt die Reihenfolge.                | Verknüpfen von Zeitreihen oder Daten, bei denen die Reihenfolge wichtig ist.                |
| `merge_asof()`               | Kombiniert Objekte, indem nahegelegene Schlüssel statt exakter Übereinstimmungen verwendet werden. | Verknüpfen von Zeitstempeln oder Sensordaten mit ungenauer Übereinstimmung.                 |
| `Series.compare()` / `DataFrame.compare()` | Zeigt Unterschiede zwischen zwei Objekten an.                                               | Identifizieren von Änderungen in Daten, z. B. vor und nach einer Aktualisierung.            |

---