![image info](https://user-images.githubusercontent.com/91945811/146929832-e78ff1f4-2739-41b1-acd3-019a39b6a42c.png)

<div style="float: right; font-size: small;">
    Erstellt von Fakher Ahmed für Data Science Institut by Fabian Rappert
</div>

## **Einführung in Regex mit Pandas**

### **Was ist Regex?**
Reguläre Ausdrücke (Regex) sind Muster, die verwendet werden, um bestimmte Zeichenfolgen in Texten zu finden, zu extrahieren oder zu manipulieren. Sie sind extrem nützlich in der Datenanalyse, insbesondere beim Bereinigen und Transformieren von Textdaten.

---

### **1. Grundlegende Regex-Syntax**
Bevor wir Regex in Pandas verwenden, schauen wir uns die wichtigsten Bausteine an:

| Regex-Muster | Bedeutung                                                                 |
|--------------|---------------------------------------------------------------------------|
| `.`          | Beliebiges Zeichen außer Zeilenumbruch                                   |
| `\d`         | Eine Ziffer (0-9)                                                        |
| `\D`         | Kein Ziffernzeichen                                                      |
| `\w`         | Ein alphanumerisches Zeichen (a-z, A-Z, 0-9, _)                          |
| `\W`         | Kein alphanumerisches Zeichen                                            |
| `\s`         | Ein Leerzeichen (Leerzeichen, Tab, etc.)                                 |
| `\S`         | Kein Leerzeichen                                                        |
| `^`          | Start der Zeichenkette                                                  |
| `$`          | Ende der Zeichenkette                                                   |
| `[]`         | Zeichenklasse (z. B. `[aeiou]` sucht nach einem Vokal)                  |
| `()`         | Gruppierung für Muster oder Extraktion                                  |
| `*`          | 0 oder mehr Wiederholungen                                              |
| `+`          | 1 oder mehr Wiederholungen                                              |
| `?`          | 0 oder 1 Wiederholung                                                   |
| `{n}`        | Genau n Wiederholungen                                                  |
| `{n,m}`      | Zwischen n und m Wiederholungen                                          |
| `\`          | Escape-Zeichen (z. B. `\.` sucht nach einem Punkt)                      |

---

### **2. Daten vorbereiten**

Wir erstellen ein Beispiel-DataFrame, mit dem wir verschiedene Regex-Operationen demonstrieren können:

```python

In [3]:
import pandas as pd

data = {
    "Name": ["Alice Wonderland", "Bob Marley", "Charlie Brown", "Dora Explorer"],
    "Email": [
        "alice@wonderland.com",
        "bob.marley@gmail.com",
        "charlie.brown@yahoo.com",
        "dora.explorer@adventure.com",
    ],
    "Phone": ["123-456-7890", "987.654.3210", "555-666-7777", "(123) 456-7890"],
    "Comment": ["Order #12345", "Query #54321", "Complaint #98765", "Feedback #67890"],
}

df = pd.DataFrame(data)
display(df)

,Name,Email,Phone,Comment
0,Alice Wonderland,alice@wonderland.com,123-456-7890,Order #12345
1,Bob Marley,bob.marley@gmail.com,987.654.3210,Query #54321
2,Charlie Brown,charlie.brown@yahoo.com,555-666-7777,Complaint #98765
3,Dora Explorer,dora.explorer@adventure.com,(123) 456-7890,Feedback #67890

---

### **3. Praktische Anwendung von Regex mit Pandas**

#### **3.1. Suche nach Text mit `str.contains()`**
`str.contains()` verwendet ein Regex-Muster, um Text in einer Spalte zu suchen. Beispiel: Finde alle E-Mails mit der Domain "gmail.com".

In [5]:
filtered_df = df[df["Email"].str.contains(r"@gmail.com", na=False)]
display(filtered_df)

         Name                 Email         Phone       Comment
1  Bob Marley  bob.marley@gmail.com  987.654.3210  Query #54321

### **Regex-Erklärung**:

Das Präfix `r` in Python steht für **"raw string"** (roher String). Es wird verwendet, um Escape-Zeichen (`\`) in Strings korrekt zu interpretieren, ohne sie speziell behandeln zu müssen.

##### **Warum wird `r` benötigt?**
In regulären Ausdrücken (`Regex`) werden viele Zeichen mit einem Backslash (`\`) verwendet, wie z. B.:
- `\d` (für eine Ziffer)
- `\w` (für ein alphanumerisches Zeichen)
- `\.` (für einen Punkt)

Wenn du in Python einen normalen String ohne `r` verwendest, musst du den Backslash doppelt schreiben (`\\`), da der Backslash im normalen String als Escape-Zeichen interpretiert wird. Das führt zu mehr Schreibaufwand und macht den Code schwerer lesbar.

**Kurz gesagt:** Das `r` erleichtert die Arbeit mit Regex und vermeidet unnötiges doppeltes Escaping. 

---


#### **3.2. Extrahieren von Text mit `str.extract()`**
Extrahiere Muster wie die Bestellnummer (`#12345`) aus der Spalte `Comment`.

In [8]:
df["Order_ID"] = df["Comment"].str.extract(r"#(\d+)")
display(df)

,Name,Email,Phone,Comment,Order_ID
0,Alice Wonderland,alice@wonderland.com,123-456-7890,Order #12345,12345
1,Bob Marley,bob.marley@gmail.com,987.654.3210,Query #54321,54321
2,Charlie Brown,charlie.brown@yahoo.com,555-666-7777,Complaint #98765,98765
3,Dora Explorer,dora.explorer@adventure.com,(123) 456-7890,Feedback #67890,67890

- **Regex-Erklärung**:
  - `#` sucht das `#`-Symbol.
  - `(\d+)`: 
    - `\d` steht für eine Ziffer (0-9).
    - `+` bedeutet "eine oder mehr Wiederholungen".
    - Die Klammern `()` gruppieren das Muster, um es zu extrahieren.

#### **3.3. Ersetzen von Text mit `str.replace()`**
Ersetze Punkte oder Klammern in Telefonnummern durch Bindestriche.

```python

In [10]:
df["Phone_Cleaned"] = df["Phone"].str.replace(r"[()]", "", regex=True)
df["Phone_Cleaned"] = df["Phone_Cleaned"].str.replace(r"[.\s]", "-", regex=True)
display(df)

,Name,Email,Phone,Comment,Order_ID,Phone_Cleaned
0,Alice Wonderland,alice@wonderland.com,123-456-7890,Order #12345,12345,123-456-7890
1,Bob Marley,bob.marley@gmail.com,987.654.3210,Query #54321,54321,987-654-3210
2,Charlie Brown,charlie.brown@yahoo.com,555-666-7777,Complaint #98765,98765,555-666-7777
3,Dora Explorer,dora.explorer@adventure.com,(123) 456-7890,Feedback #67890,67890,123-456-7890

- **Regex-Erklärung**:
  - `[()]`: 
    - `()` sucht nach Klammern.
    - Die Zeichen sind in eckigen Klammern gruppiert, was bedeutet, dass eines davon ersetzt wird.
  - `[.\s()]`: 
    - `.` sucht nach einem Punkt.
    - `\s` sucht nach Leerzeichen (oder Tabs).
  - `-` ist der Ersatzwert.
  -

---

### **4. Kombination von Regex und Pandas**

#### **4.1. Benutzerdefinierte Funktion mit Regex**
Kategorisiere E-Mails basierend auf ihrer Domain.

In [22]:
def categorize_email(email):
    if pd.isna(email):
        return "Unknown"
    if "gmail.com" in email:
        return "Personal"
    elif "yahoo.com" in email:
        return "Personal"
    else:
        return "Work"


df["Email_Category"] = df["Email"].apply(categorize_email)
display(df)

,Name,Email,Phone,Comment,Order_ID,Phone_Cleaned,First_Name,Last_Name,Standard_Phone,Phone_International,Cleaned_Comment,Trimmed_Name,Email_Category
0,Alice Wonderland,alice@wonderland.com,123-456-7890,Order #12345,12345,123-456-7890,Alice,Wonderland,123-456-7890,+49-123-456-7890,Order 12345,Alice Wonderland,Work
1,Bob Marley,bob.marley@gmail.com,987.654.3210,Query #54321,54321,987-654-3210,Bob,Marley,NaN,+49-987-654-3210,Query 54321,Bob Marley,Personal
2,Charlie Brown,charlie.brown@yahoo.com,555-666-7777,Complaint #98765,98765,555-666-7777,Charlie,Brown,555-666-7777,+49-555-666-7777,Complaint 98765,Charlie Brown,Personal
3,Dora Explorer,dora.explorer@adventure.com,(123) 456-7890,Feedback #67890,67890,123-456-7890,Dora,Explorer,NaN,+49-123-456-7890,Feedback 67890,Dora Explorer,Work

---

### **Zusammenfassung**

#### Was du gelernt hast:
1. **String- und Regex-Grundlagen**: Suche, Extrahieren und Ersetzen.
2. **Kombination mit Pandas**: Verwendung von `str.contains()`, `str.extract()` und `str.replace()`.

Regex ist eine Schlüsselkompetenz für die Verarbeitung und Bereinigung von Textdaten in Python und Pandas. Hierbei gibt es viele Möglichkeiten und viele Befehle zur Mustererkennung. Dies soll erstmal als Grundlagen dienen, um das Konzept zu verstehen. Die einzelnen Befehle kannst du jederzeit nachschauen! 😊