![image info](https://user-images.githubusercontent.com/91945811/146929832-e78ff1f4-2739-41b1-acd3-019a39b6a42c.png)

## Aufgabensammlung zum Thema Datenaufbereitung

### Aufgabe 1: Daten kombinieren (Verkäufe aus Januar und Februar)

#### Ziel:
Du hast zwei Datensätze, die Verkaufsdaten aus Januar und Februar enthalten (*sales_january.csv* und *sales_february.csv*). 
Kombiniere diese Daten zu einem einzigen Datensatz und füge eine neue Spalte hinzu, 
die den Gesamtumsatz aus beiden Monaten berechnet.
Da die Verkaufsdaten eine einfache Struktur haben (Produkt Spalte ist identisch), brauchst du sie lediglich spaltenweise zu verketten.

In [3]:
import pandas as pd

# Datensätze laden
sales_january = pd.read_csv("sales/sales_january.csv")
sales_february = pd.read_csv("sales/sales_february.csv")

# Datensätze anzeigen
print("Verkaufsdaten Januar: ")
display(sales_january)

print("Verkaufsdaten Februar: ")
display(sales_february)

# Daten kombinieren
sales_combined = pd.concat([sales_january, sales_february], axis=1)

# Gesamtumsatz berechnen
sales_combined["Gesamtumsatz"] = sales_combined["Umsatz_Jan"] + sales_combined["Umsatz_Feb"]

# Ergebnis anzeigen
print("Verkaufsdaten kombiniert: ")

display(sales_combined)

Verkaufsdaten Januar:

   Produkt  Umsatz_Jan
0       P1         865
1       P2         703
2       P3         713
3       P4         691
4       P5         450
..     ...         ...
95     P96         666
96     P97         984
97     P98         728
98     P99         316
99    P100         743

[100 rows x 2 columns]

Verkaufsdaten Februar:

   Produkt  Umsatz_Feb
0       P1         363
1       P2         708
2       P3         355
3       P4         549
4       P5         718
..     ...         ...
95     P96         863
96     P97         367
97     P98         643
98     P99         211
99    P100         249

[100 rows x 2 columns]

Verkaufsdaten kombiniert:

   Produkt  Umsatz_Jan Produkt  Umsatz_Feb  Gesamtumsatz
0       P1         865      P1         363          1228
1       P2         703      P2         708          1411
2       P3         713      P3         355          1068
3       P4         691      P4         549          1240
4       P5         450      P5         718          1168
..     ...         ...     ...         ...           ...
95     P96         666     P96         863          1529
96     P97         984     P97         367          1351
97     P98         728     P98         643          1371
98     P99         316     P99         211           527
99    P100         743    P100         249           992

[100 rows x 5 columns]

Eine allgemeine (bessere) Lösung wäre eher das "Verknüpfen" der Datensätze über die Produkt-Spalte mittels `merge()`. Denn so haben wir die Spalte Produkt im neuen Datensatz doppelt...

---

### Aufgabe 2: Kunden und Bestellungen verknüpfen

#### Ziel:
Verknüpfe die beiden Datensätze *customers.csv* und *orders.csv*, um eine Übersicht zu erstellen, 
welche Kunden welche Produkte bestellt haben.

In [6]:
# Datensätze laden
customers = pd.read_csv("sales/customers.csv")
orders = pd.read_csv("sales/orders.csv")

# Datensätze anzeigen
print("Kunden: ")
display(customers)

print("Bestellungen: ")
display(orders)

# Verknüpfung der Datensätze
customer_orders = pd.merge(customers, orders, on="CustomerID", how="left")

print("Kunden mit Bestellung: ")
# Ergebnis anzeigen
display(customer_orders)

Kunden:

    CustomerID          Name       City
0           C1    Customer_1    Hamburg
1           C2    Customer_2  Frankfurt
2           C3    Customer_3  Frankfurt
3           C4    Customer_4    Hamburg
4           C5    Customer_5     Berlin
..         ...           ...        ...
195       C196  Customer_196    Cologne
196       C197  Customer_197    Cologne
197       C198  Customer_198     Munich
198       C199  Customer_199     Munich
199       C200  Customer_200    Hamburg

[200 rows x 3 columns]

Bestellungen:

    OrderID CustomerID     Product  Quantity
0        O1        C52     Monitor         3
1        O2         C2     Monitor         1
2        O3        C14     Monitor         4
3        O4        C26     Monitor         3
4        O5        C82     Monitor         1
..      ...        ...         ...       ...
495    O496       C187     Monitor         3
496    O497        C95     Monitor         1
497    O498        C80  Smartphone         4
498    O499        C45  Smartphone         4
499    O500        C62     Printer         3

[500 rows x 4 columns]

Kunden mit Bestellung:

    CustomerID          Name       City OrderID     Product  Quantity
0           C1    Customer_1    Hamburg     O28     Printer       2.0
1           C2    Customer_2  Frankfurt      O2     Monitor       1.0
2           C2    Customer_2  Frankfurt     O47      Tablet       1.0
3           C2    Customer_2  Frankfurt    O115  Smartphone       1.0
4           C2    Customer_2  Frankfurt    O165     Printer       4.0
..         ...           ...        ...     ...         ...       ...
510       C198  Customer_198     Munich    O484     Monitor       2.0
511       C199  Customer_199     Munich    O233  Smartphone       1.0
512       C199  Customer_199     Munich    O250  Smartphone       2.0
513       C200  Customer_200    Hamburg    O192      Laptop       4.0
514       C200  Customer_200    Hamburg    O467      Laptop       2.0

[515 rows x 6 columns]

---

### Aufgabe 3: Umsatzdaten vergleichen

#### Ziel:
Kombiniere die Umsatzdaten aus zwei Filialen (store_revenue CSVs), sodass die monatlichen Umsätze nebeneinander dargestellt werden. 
Berechne außerdem die Differenz zwischen den Umsätzen der beiden Filialen.
Tipp: Verwende `index_col=0` Parameter beim Laden der CSVs, um anschließend `join()`zu verwenden.

In [8]:
# Datensätze laden
store1_revenue = pd.read_csv("sales/store1_revenue.csv", index_col=0)
store2_revenue = pd.read_csv("sales/store2_revenue.csv", index_col=0)

print("Filialen einzeln: ")
# Ergebnis anzeigen
display(store1_revenue)
display(store2_revenue)


# Daten kombinieren
combined_revenue = store1_revenue.join(store2_revenue, lsuffix="_Store1", rsuffix="_Store2")

# Differenz berechnen
combined_revenue["Store2_Difference_from_Store1"] = (
    combined_revenue["Revenue_Store1"] - combined_revenue["Revenue_Store2"]
)

# Ergebnis anzeigen
display(combined_revenue)

Filialen einzeln:

         Revenue
2022-01    13804
2022-02     9794
2022-03     9089
2022-04     6904
2022-05     9778
2022-06    10750
2022-07     8476
2022-08     7323
2022-09     9512
2022-10     9599
2022-11    14672
2022-12    13518
2023-01     5779
2023-02     8172
2023-03     6333
2023-04    14547
2023-05    13660
2023-06     7870
2023-07    12759
2023-08     9767
2023-09    12503
2023-10    12918
2023-11     8628
2023-12    14252
2024-01     9237
2024-02     9725
2024-03    11878
2024-04     7360
2024-05    10290
2024-06    13046
2024-07     7520
2024-08     6012
2024-09     6036
2024-10     9852
2024-11    11373
2024-12    13033

         Revenue
2022-01    10124
2022-02    11340
2022-03     9622
2022-04    12039
2022-05     5939
2022-06     4096
2022-07    11897
2022-08    13375
2022-09     5286
2022-10     7866
2022-11     9156
2022-12     6673
2023-01     4283
2023-02     8788
2023-03     4010
2023-04     7336
2023-05    12026
2023-06    12044
2023-07    10686
2023-08     4274
2023-09     8039
2023-10     9175
2023-11     4954
2023-12    11820
2024-01     4650
2024-02    11794
2024-03    12648
2024-04    13212
2024-05     6868
2024-06     6467
2024-07     7321
2024-08     9618
2024-09     7523
2024-10     6910
2024-11     8614
2024-12     5269

         Revenue_Store1  Revenue_Store2  Store2_Difference_from_Store1
2022-01           13804           10124                           3680
2022-02            9794           11340                          -1546
2022-03            9089            9622                           -533
2022-04            6904           12039                          -5135
2022-05            9778            5939                           3839
2022-06           10750            4096                           6654
2022-07            8476           11897                          -3421
2022-08            7323           13375                          -6052
2022-09            9512            5286                           4226
2022-10            9599            7866                           1733
2022-11           14672            9156                           5516
2022-12           13518            6673                           6845
2023-01            5779            4283                           1496
2023-02            8172            8788                           -616
2023-03            6333            4010                           2323
2023-04           14547            7336                           7211
2023-05           13660           12026                           1634
2023-06            7870           12044                          -4174
2023-07           12759           10686                           2073
2023-08            9767            4274                           5493
2023-09           12503            8039                           4464
2023-10           12918            9175                           3743
2023-11            8628            4954                           3674
2023-12           14252           11820                           2432
2024-01            9237            4650                           4587
2024-02            9725           11794                          -2069
2024-03           11878           12648                           -770
2024-04            7360           13212                          -5852
2024-05           10290            6868                           3422
2024-06           13046            6467                           6579
2024-07            7520            7321                            199
2024-08            6012            9618                          -3606
2024-09            6036            7523                          -1487
2024-10            9852            6910                           2942
2024-11           11373            8614                           2759
2024-12           13033            5269                           7764