![image info](https://user-images.githubusercontent.com/91945811/146929832-e78ff1f4-2739-41b1-acd3-019a39b6a42c.png)

# Titanic-Datensatz: Deskriptive Statistik & Korrelation

## Einführung & Motivation

Der Titanic-Datensatz ist einer der bekanntesten und meistgenutzten Datensätze in der Statistik und im maschinellen Lernen. Er enthält Informationen über die Passagiere der Titanic, die 1912 sank, und erlaubt es, spannende Zusammenhänge zwischen Merkmalen wie Alter, Geschlecht, Ticketklasse und Überlebensrate zu analysieren. 

In dieser Übung wirst du grundlegende deskriptive Methoden anwenden, um den Datensatz zu untersuchen. Ziel ist es, zentrale statistische Konzepte wie Lagemaße, Streuung und Korrelationen in der Praxis zu verstehen. Wir beschäftigen uns auch mit Datenqualität und explorativer Datenanalyse.

Am Ende wirst du in der Lage sein:
- Einen Überblick über den Datensatz zu gewinnen,
- Fehlende Werte zu identifizieren und zu behandeln,
- Statistische Maßzahlen zu berechnen,
- Gruppierte Analysen durchzuführen,
- Korrelationen zu interpretieren.

## Vorbereitung: Titanic-Datensatz laden

In [3]:
### Laden über `seaborn`
import seaborn as sns

titanic = sns.load_dataset("titanic")
display(titanic)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True


---

## 1. Grundlegender Datenüberblick

### Aufgabe: Erste Inspektion
- Nutze `describe()`, `shape`, und `info()`, um die Struktur des Datensatzes zu untersuchen.

**Musterlösung:**

In [5]:
# Ausgabe der Form des Datensatzes (Anzahl der Zeilen und Spalten)

In [6]:
# Überblick über Spaltennamen, Datentypen und fehlende Werte

In [7]:
# Anzeige diskriptiven Statistiken

In [8]:
# Anzeige diskriptiven Statistiken

**Erklärung:**
Diese ersten Analysen helfen uns, die Struktur des Datensatzes zu verstehen. Wir sehen sofort:
- Welche Spalten enthalten welche Werte,
- Welche Datentypen vorliegen (numerisch, kategorisch),
- Ob es fehlende Werte gibt.

### Aufgabe: Fehlende Werte prüfen
- Verwende `isnull().sum()`, um fehlende Werte (`NaN`) in den Spalten zu analysieren.
- Entscheide, ob du sie entfernen (`dropna()`) oder durch sinnvolle Werte ersetzen möchtest (`fillna()`).

**Musterlösung:**

In [10]:
# Anzeige der Anzahl fehlender Werte je Spalte

**Erklärung:**
Fehlende Werte können Analysen beeinflussen. 
- Besonders das Alter (`age`) hat fehlende Werte, weshalb wir den Median als Ersatzwert nutzen. Ältere Passagiere waren oft in höheren Klassen, daher kann ein Median pro Geschlecht und Klasse sinnvoll sein. Alternativ könnten Werte entfernt werden, aber das würde Daten verlieren.
- Kategorische Spalten embarked und embark_town: Beide Spalten hängen zusammen (da embark_town der ausgeschriebene Name von embarked ist). Hier bietet sich das häufigste Vorkommen (mode()) als Ersatz an. Da nur 2 Werte fehlen, ist der häufigste Wert (mode()[0]) eine sinnvolle Wahl.
- Spalte deck hat 688 fehlende Werte: Fast 80% fehlen → Droppen sinnvoll, da kaum verwertbare Daten vorhanden. Falls die Spalte wichtig erscheint, könnte man "U" (Unknown) als Ersatzwert nehmen.

### Aufgabe: Datentypen analysieren
- Prüfe, ob es sinnvoll ist, `pclass` als Kategorie (`category`) zu speichern.
- Überlege, ob `age` oder `fare` in Kategorien (z.B. Altersgruppen) unterteilt werden sollten.

**Musterlösung:**

In [13]:
display(titanic)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

**Erklärung:**
Durch die Umwandlung von `pclass` in eine Kategorie können Speicherplatz gespart und Analysen vereinfacht werden. Das Alter wird in Gruppen unterteilt, um es besser auswerten zu können.

---

## 2. Deskriptive Statistik


### Aufgabe: Gruppenvergleiche
- Berechne den Durchschnitt von `age` und `fare` für die Gruppen `sex`.

**Musterlösung:**

**Erklärung:**
- Diese Berechnung zeigt, ob es **Unterschiede zwischen Männern und Frauen** bezüglich Altersstruktur und Ticketpreisen gab.

### Aufgabe: Korrelation berechnen
- Berechne die **Pearson-Korrelation** zwischen `age` und `fare`.

**Musterlösung:**

**Erklärung:**

Der Pearson-Korrelationskoeffizient ist eine statistische Kennzahl, die den linearen Zusammenhang zwischen zwei numerischen Variablen misst.
Der Pearson-Korrelationskoeffizient zwischen age und fare ist nahe 0, was bedeutet, dass kein signifikanter Zusammenhang zwischen dem Alter und dem Ticketpreis besteht.
Dies deutet darauf hin, dass das Alter einer Person keinen starken Einfluss darauf hatte, wie viel für das Ticket bezahlt wurde. 

---

### Aufgabe: Ausreißer identifizieren
- Bestimme Werte von `fare`, die größer sind als `mean + 3*std()`.

**Musterlösung:**

### Aufgabe 8: Min, Max und Quartile analysieren
- Bestimme `min()` und `max()` für `fare`.
- Bestimme den **Interquartilsabstand (IQR = 75 % - 25 %)**.

**Musterlösung:**

---

## 4. Gruppenunterschiede

### Aufgabe: Vergleich Überlebender vs. Nicht-Überlebender
- Berechne den Durchschnitt von `age` und `fare` für `survived == 1` und `survived == 0`.

**Musterlösung:**

### Aufgabe: Ticketklasse untersuchen
- Berechne den Durchschnitt von `age` und `fare` pro `pclass`.

**Musterlösung:**

---

## Fazit

Diese Übung hilft dir, zentrale Methoden der deskriptiven Statistik anzuwenden und die Struktur realer Datensätze zu verstehen. Mit weiteren Analysen könnten **Machine Learning Modelle** trainiert oder **Vorhersagen über das Überleben** getroffen werden.

**Viel Erfolg beim Analysieren!**